argo-cd:
  configs:
    params:
      server.insecure: "false"
    cm:
      url: https://argo-cd.<YOUR_TAILSCALE_DOMAIN>.ts.net
      admin.enabled: "false"
      dex.config: |
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $dex.github.clientId
            clientSecret: $dex.github.clientSecret
            loadAllGroups: false
        staticClients:
        - id: argo-workflows
          name: Argo Workflows
          secret: $dex.workflows.clientSecret
          redirectURIs:
          - https://argo-workflows.<YOUR_TAILSCALE_DOMAIN>.ts.net/oauth2/callback
        - id: atlantis-oauth2-proxy
          name: Atlantis
          secret: $dex.atlantis.clientSecret
          redirectURIs:
          - https://atlantis.<YOUR_TAILSCALE_DOMAIN>.ts.net/oauth2/callback
        - id: longhorn-oauth2-proxy
          name: Longhorn
          secret: $dex.longhorn.clientSecret
          redirectURIs:
          - https://longhorn.<YOUR_TAILSCALE_DOMAIN>.ts.net/oauth2/callback
        - id: grafana
          name: Grafana
          secret: $dex.grafana.clientSecret
          redirectURIs:
          - https://grafana.<YOUR_TAILSCALE_DOMAIN>.ts.net/login/generic_oauth
        - id: ntfy-oauth2-proxy
          name: ntfy
          secret: $dex.ntfy.clientSecret
          redirectURIs:
          - https://ntfy.<YOUR_TAILSCALE_DOMAIN>.ts.net/oauth2/callback
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, <YOUR_EMAIL>, role:admin
      scopes: "[groups, email]"

  crds:
    install: true

  dex:
    enabled: true
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  notifications:
    enabled: false

  server:
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  repoServer:
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 1024Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  applicationSet:
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  controller:
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1024Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack

  redis:
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
