apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailscale
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: oauth2-proxy-longhorn
      port:
        number: 80
  tls:
    - hosts:
        - longhorn
