apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-workflows-tailscale
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - argo-workflows
  defaultBackend:
    service:
      name: argo-workflows-server
      port:
        number: 2746
