apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis-tailscale
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: oauth2-proxy-atlantis
      port:
        number: 80
  tls:
    - hosts:
        - atlantis
