apiVersion: v1
kind: Service
metadata:
  name: alertmanager-ntfy-bridge
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: alertmanager-ntfy-bridge
  ports:
    - port: 80
      targetPort: 8080
