image:
  repository: cloudflare/cloudflared
  tag: "2026.1.2"
  pullPolicy: IfNotPresent

dns:
  port: 53
  upstreams:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
hostNetwork: true

nodeSelector:
  kubernetes.io/hostname: k3s-dns

tolerations:
  - key: dedicated
    operator: Equal
    value: dns
    effect: NoSchedule
