apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: prepare-longhorn-disk
  namespace: {{ .Release.Namespace }}
spec:
  entrypoint: prepare-disk
  serviceAccountName: argo-workflow
  ttlStrategy:
    secondsAfterCompletion: 86400
  arguments:
    parameters:
    - name: host_ip
      value: ""
  templates:
  - name: prepare-disk
    inputs:
      parameters:
      - name: host_ip
      artifacts:
      - name: repo
        path: /workspace/repo
        git:
          repo: https://github.com/murrou-cell/home-cloud
          revision: main
          usernameSecret:
            name: github-credentials
            key: username
          passwordSecret:
            name: github-credentials
            key: token
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    container:
      image: cytopia/ansible:latest-tools
      command: [sh, /workspace/repo/ansible/scripts/prepare-longhorn-disk.sh]
      env:
      - name: HOST_IP
        value: "{{ "{{inputs.parameters.host_ip}}" }}"
      volumeMounts:
      - name: ssh-key
        mountPath: /ssh
        readOnly: true
    volumes:
    - name: ssh-key
      secret:
        secretName: {{ .Values.ansibleSshKeySecret | quote }}
        defaultMode: 0400
