apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: proxmox-cluster-create
  namespace: {{ .Release.Namespace }}
spec:
  entrypoint: create-cluster
  serviceAccountName: argo-workflow
  ttlStrategy:
    secondsAfterCompletion: 86400
  arguments:
    parameters:
    - name: pve_ip
      value: {{ .Values.proxmoxPrimaryIp | quote }}
    - name: cluster_name
      value: {{ .Values.proxmoxClusterName | quote }}
  templates:
  - name: create-cluster
    inputs:
      parameters:
      - name: pve_ip
      - name: cluster_name
      artifacts:
      - name: repo
        path: /workspace/repo
        git:
          repo: https://github.com/murrou-cell/home-cloud
          revision: main
          usernameSecret:
            name: github-credentials
            key: username
          passwordSecret:
            name: github-credentials
            key: token
    nodeSelector:
      kubernetes.io/hostname: k3s-ops
    container:
      image: cytopia/ansible:latest-tools
      command: [sh, /workspace/repo/ansible/scripts/proxmox-cluster-create.sh]
      env:
      - name: PVE_IP
        value: "{{ "{{inputs.parameters.pve_ip}}" }}"
      - name: CLUSTER_NAME
        value: "{{ "{{inputs.parameters.cluster_name}}" }}"
      volumeMounts:
      - name: ssh-key
        mountPath: /ssh
        readOnly: true
    volumes:
    - name: ssh-key
      secret:
        secretName: {{ .Values.ansibleSshKeySecret | quote }}
        defaultMode: 0400
